# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

version = "0.1"  

[rpc]
laddr = "tcp://127.0.0.1:26657"
cors_allowed_origins = []
cors_allowed_methods = [ "HEAD",  "GET",  "POST", ]
cors_allowed_headers = [ "Origin",  "Accept",  "Content-Type",  "X-Requested-With",  "X-Server-Time", ]
grpc_laddr = ""
grpc_max_open_connections = 900
unsafe = false
max_open_connections = 900
max_subscription_clients = 100
max_subscriptions_per_client = 5
experimental_subscription_buffer_size = 200
experimental_websocket_write_buffer_size = 200
experimental_close_on_slow_client = false
timeout_broadcast_tx_commit = "10s"
max_body_bytes = 1000000
max_header_bytes = 1048576
tls_cert_file = ""
tls_key_file = ""
pprof_laddr = ""

[p2p]
laddr = "tcp://0.0.0.0:2300"
external_address = ""
seeds = ""
persistent_peers = ""
max_num_inbound_peers = 40
max_num_outbound_peers = 10
unconditional_peer_ids = ""
persistent_peers_max_dial_period = "0s"
flush_throttle_timeout = "100ms"
max_packet_msg_payload_size = 1024
send_rate = 5120000
recv_rate = 5120000
pex = true
seed_mode = false
private_peer_ids = ""
allow_duplicate_ip = false
handshake_timeout = "20s"
dial_timeout = "3s"

[statesync]
enable = false
temp_dir = "./podsync_temp"
rpc_servers = []
pod_trust_period = "168h0m0s"
pod_trust_height = 0
pod_trust_hash = ""
pod_discovery_time = "15m0s"
pod_request_timeout = "5s"
pod_chunk_fetchers = 4

[consensus]
wal_file = "data/pods.wal/wal"
timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "1s"
skip_timeout_commit = false

double_sign_check_height = 0

# Data Availability Layer Configuration
[da]
# Add specific configuration keys and values for DA here


# Station Configuration
[station]
# Add specific configuration keys and values for Station here


# Junction Configuration
[junction]
# Add specific configuration keys and values for Junction here

